### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by mattfaucher** [johnludwigm/PyApartments#1]
Hey, I was thinking of writing something like this for apartments.com but found your repository! I was wondering if you could add more docs on how to use this API, I'd preferably want to use the functions to pull information out for my own app

**Comment by johnludwigm** [comment]
Hey Matt,

I am no longer maintaining this project. If I were in your position, I'd try to find an actual REST API as opposed to a webscraper. It would be faster to use and probably require less maintenance.
